export const metadata = { title: "Privacy Policy", description: "Easy HomeSource privacy policy." };

const privacySections = [
  { heading: "Privacy Policy", body: ["Last updated Feb 3, 2026", "This privacy notice for Trove Homes, Inc. doing business as Trove describes how and why we might collect, store, use, and/or share your information when you use our Services, such as when you visit our website or engage with us in other related ways, including sales, marketing, or events.", "Questions or concerns? Reading this privacy notice will help you understand your privacy rights and choices. If you do not agree with our policies and practices, please do not use our Services. If you still have questions or concerns, please contact us at support@buildtrove.com."] },
  { heading: "Summary of Key Points", body: ["When you visit, use, or navigate our Services, we may process personal information depending on how you interact with us and the Services, the choices you make, and the products and features you use.", "We do not process sensitive personal information. We do not receive any information from third parties.", "We process your information to provide, improve, and administer our Services, communicate with you, for security and fraud prevention, and to comply with law. We may process information for other purposes with your consent.", "We may share information in specific situations and with specific third parties. We have organizational and technical processes and procedures in place to protect your personal information, but no electronic transmission or storage technology can be guaranteed to be 100% secure.", "Depending on where you are located geographically, applicable privacy law may mean you have certain rights regarding your personal information. The easiest way to exercise your rights is by submitting a data subject access request or by contacting us."] },
  { heading: "1. What Information Do We Collect?", body: ["We collect personal information that you voluntarily provide to us when you register on the Services, express an interest in obtaining information about us or our products and Services, participate in activities on the Services, or otherwise contact us.", "The personal information we collect may include names, phone numbers, email addresses, mailing addresses, and passwords. We do not process sensitive information.", "We may collect payment data necessary to process your payment if you make purchases. Payment data is stored by Stripe. We may provide you with the option to register using social media account details.", "We automatically collect certain information when you visit, use, or navigate the Services. This may include IP address, browser and device characteristics, operating system, language preferences, referring URLs, device name, country, location, usage information, and technical information needed for security, operation, analytics, and reporting.", "Like many businesses, we collect information through cookies and similar technologies, including log and usage data, device data, and location data."] },
  { heading: "2. How Do We Process Your Information?", body: ["We process your information to provide, improve, and administer our Services, communicate with you, for security and fraud prevention, and to comply with law. We may process your information for other purposes with your consent.", "We may process information to facilitate account creation and authentication, manage user accounts, send marketing and promotional communications, deliver targeted advertising, evaluate and improve our Services, identify usage trends, and determine the effectiveness of marketing and promotional campaigns."] },
  { heading: "3. When and With Whom Do We Share Your Personal Information?", body: ["We may share information in specific situations described in this notice and with specific third parties.", "We may share or transfer information in connection with, or during negotiations of, any merger, sale of company assets, financing, or acquisition of all or a portion of our business.", "When we use Google Maps Platform APIs, we may share information with certain Google Maps Platform APIs. We obtain and store on your device cache your location, and you may revoke consent by contacting us."] },
  { heading: "4. Cookies and Tracking Technologies", body: ["We may use cookies and similar tracking technologies, such as web beacons and pixels, to access or store information.", "We partner with Microsoft Clarity and Microsoft Advertising to capture how users interact with the website through behavioral metrics, heatmaps, and session replay to improve and market products and services."] },
  { heading: "5. Social Logins", body: ["If you choose to register or log in using a third-party social media account, we may receive profile information from your social media provider. We use that information only for purposes described in this privacy notice or made clear to you on the relevant Services."] },
  { heading: "6. How Long Do We Keep Your Information?", body: ["We keep information for as long as necessary to fulfill the purposes outlined in this privacy notice unless otherwise required by law. When we have no ongoing legitimate business need to process personal information, we will delete or anonymize it, or securely store and isolate it until deletion is possible."] },
  { heading: "7. How Do We Keep Your Information Safe?", body: ["We have implemented appropriate and reasonable technical and organizational security measures designed to protect the security of personal information we process.", "No electronic transmission over the Internet or information storage technology can be guaranteed to be 100% secure. You should access the Services only within a secure environment."] },
  { heading: "8. Do We Collect Information From Minors?", body: ["We do not knowingly solicit data from or market to children under 18 years of age. If we learn that personal information from users less than 18 years of age has been collected, we will deactivate the account and take reasonable measures to promptly delete such data from our records.", "If you become aware of any data we may have collected from children under age 18, please contact support@buildtrove.com."] },
  { heading: "9. What Are Your Privacy Rights?", body: ["You may review, change, or terminate your account at any time. If we rely on consent to process your personal information, you have the right to withdraw consent at any time by contacting us.", "You can unsubscribe from marketing and promotional communications at any time by clicking the unsubscribe link in emails we send or by contacting us. We may still communicate for non-marketing purposes, including service-related messages necessary for account administration, service requests, and similar purposes.", "Most browsers accept cookies by default. You can usually set your browser to remove or reject cookies, which may affect certain features or services."] },
  { heading: "10. Controls for Do-Not-Track Features", body: ["Most web browsers and some mobile operating systems and applications include a Do-Not-Track feature. At this stage no uniform technology standard for recognizing and implementing DNT signals has been finalized, so we do not currently respond to DNT browser signals or similar mechanisms."] },
  { heading: "11. United States Resident Privacy Rights", body: ["If you are a resident of California, Colorado, Connecticut, Utah, or Virginia, you may have specific rights regarding access to your personal information.", "In the past twelve months, collected categories may include identifiers and personal information as defined in the California Customer Records statute. We do not process consumer sensitive personal information.", "We have not disclosed, sold, or shared personal information to third parties for a business or commercial purpose in the preceding twelve months. We will not sell or share personal information in the future belonging to website visitors, users, and other consumers.", "Residents may have rights to know, access, correct, delete, obtain a copy of personal data, opt out of certain processing, and appeal decisions, depending on applicable state law. Requests may be submitted by email at support@buildtrove.com or through a data subject access request."] },
  { heading: "12. Updates to This Notice", body: ["We may update this privacy notice from time to time. The updated version will be indicated by an updated revised date and will be effective as soon as it is accessible. We encourage you to review this privacy notice frequently."] },
  { heading: "13. Contact Us", body: ["If you have questions or comments about this notice, you may email support@buildtrove.com or contact us by post at Trove Homes, Inc., 104 Birch Way, San Rafael, CA 94903, United States."] },
  { heading: "14. Review, Update, or Delete Your Data", body: ["Based on the applicable laws of your country, you may have the right to request access to the personal information we collect from you, change that information, or delete it. To request review, update, or deletion, please submit a data subject access request."] }
];

export default function PrivacyPolicyPage() {
  return <main className="px-4 py-12"><article className="mx-auto max-w-4xl rounded-[2rem] border border-borderGray bg-white p-8"><p className="font-black text-ehsBlue">Privacy Policy</p>{privacySections.map((section, index) => <section key={section.heading} className={index === 0 ? "mt-2" : "mt-8"}><h1 className={index === 0 ? "text-4xl font-black text-ehsBlack" : "text-2xl font-black text-ehsBlack"}>{section.heading}</h1><div className="mt-4 space-y-4 leading-8 text-ehsBlack/75">{section.body.map((paragraph) => <p key={paragraph}>{paragraph}</p>)}</div></section>)}</article></main>;
}
