import type { ReactNode } from "react";
import { siteInfo } from "@/data/site";

export const metadata = { title: "Privacy Policy", description: "Easy HomeSource privacy policy for website visitors and home shoppers." };

export default function PrivacyPage() {
  return <main className="px-4 py-12"><section className="mx-auto max-w-4xl rounded-[2rem] bg-white p-8 shadow-sm ring-1 ring-ehsBlue/10"><p className="font-black text-ehsDeepBlue">Easy HomeSource</p><h1 className="mt-2 text-4xl font-black text-ehsNavy">Privacy Policy</h1><p className="mt-3 text-sm font-semibold text-ehsNavy/60">Last updated: July 7, 2026</p><div className="mt-8 space-y-6 leading-8 text-ehsNavy/75"><p>Easy HomeSource respects your privacy. This policy explains how we collect and use information when you browse our website, request pricing, ask about financing options, schedule a tour, call, text, or submit a contact form.</p><Section title="Information we collect">We may collect your name, phone number, email address, preferred home, budget range, financing interests, delivery or setup location, and any message you choose to provide. We may also collect basic website analytics such as pages visited, device type, referral source, and general location information.</Section><Section title="How we use information">We use information to respond to your requests, provide home and pricing information, discuss financing options, coordinate tours, improve the website, and maintain business records. Home availability, pricing, financing, delivery, setup, permits, taxes, fees, and final project costs remain subject to final quote and approval where applicable.</Section><Section title="SMS and contact consent">By submitting a form or contacting Easy HomeSource, you authorize us to contact you by phone, email, call, or text about your inquiry. Message and data rates may apply. Consent is not a condition of purchase, and you may request that we stop contacting you at any time.</Section><Section title="Sharing information">We do not sell your personal information. We may share information with service providers, lenders or financing partners at your request, delivery/setup professionals, technology providers, or legal and compliance advisors when needed to respond to your inquiry or operate our business.</Section><Section title="Your choices">You may contact us to update your information or request that we stop marketing communications. Some records may be retained when needed for legitimate business, legal, or compliance purposes.</Section><Section title="Contact">Questions about this policy can be sent to Easy HomeSource at {siteInfo.email} or by calling {siteInfo.phoneDisplay}. Our office is located at {siteInfo.address}.</Section></div></section></main>;
}

function Section({ title, children }: { title: string; children: ReactNode }) { return <section><h2 className="text-2xl font-black text-ehsNavy">{title}</h2><p className="mt-2">{children}</p></section>; }
