"use client";

import { useMemo, useState } from "react";
import { HomeCard } from "@/components/HomeCard";
import type { Home } from "@/data/homes";

type Sort = "price-asc" | "price-desc" | "sqft-asc" | "sqft-desc" | "beds-asc" | "beds-desc" | "newest";
const priceNumber = (home: Home) => home.salePrice ?? home.startingPrice ?? Number.POSITIVE_INFINITY;

export function HomesBrowser({ homes }: { homes: Home[] }) {
  const [search, setSearch] = useState(""); const [bedrooms, setBedrooms] = useState("Any"); const [bathrooms, setBathrooms] = useState("Any"); const [priceMax, setPriceMax] = useState("Any"); const [sqftMin, setSqftMin] = useState("Any"); const [sort, setSort] = useState<Sort>("newest"); const [flags, setFlags] = useState({ featured: false, onDisplay: false, newArrival: false, specialOffer: false });
  const filteredHomes = useMemo(() => homes.filter((home) => {
    const q = search.trim().toLowerCase(); const p = priceNumber(home);
    return (!q || [home.name, home.modelNumber, home.size].some((v) => (v ?? "").toLowerCase().includes(q))) && (bedrooms === "Any" || home.bedrooms != null && home.bedrooms >= Number(bedrooms)) && (bathrooms === "Any" || home.bathrooms != null && home.bathrooms >= Number(bathrooms)) && (priceMax === "Any" || p <= Number(priceMax)) && (sqftMin === "Any" || home.squareFeet != null && home.squareFeet >= Number(sqftMin)) && (!flags.featured || home.isFeatured) && (!flags.onDisplay || home.isOnDisplay) && (!flags.newArrival || home.isNewArrival) && (!flags.specialOffer || home.isSpecialOffer);
  }).sort((a, b) => { if (sort === "price-asc") return priceNumber(a) - priceNumber(b); if (sort === "price-desc") return priceNumber(b) - priceNumber(a); if (sort === "sqft-asc") return (a.squareFeet ?? Infinity) - (b.squareFeet ?? Infinity); if (sort === "sqft-desc") return (b.squareFeet ?? -Infinity) - (a.squareFeet ?? -Infinity); if (sort === "beds-asc") return (a.bedrooms ?? Infinity) - (b.bedrooms ?? Infinity); if (sort === "beds-desc") return (b.bedrooms ?? -Infinity) - (a.bedrooms ?? -Infinity); return b.createdAt.localeCompare(a.createdAt); }), [bathrooms, bedrooms, flags, homes, priceMax, search, sort, sqftMin]);
  return <section className="mt-8"><div className="rounded-[1.75rem] border border-borderGray bg-white p-4 shadow-sm sm:p-5"><div className="grid gap-4 md:grid-cols-4 md:items-end"><label className="text-sm font-black text-ehsBlack md:col-span-2">Search<input value={search} onChange={(e) => setSearch(e.target.value)} placeholder="Search by home name, model, or size" className="mt-2 w-full rounded-2xl border border-borderGray bg-white px-4 py-3 font-semibold text-ehsBlack" /></label><Select label="Bedrooms" value={bedrooms} setValue={setBedrooms} options={["Any", "1", "2", "3", "4", "5"]} suffix="+ bedrooms" /><Select label="Bathrooms" value={bathrooms} setValue={setBathrooms} options={["Any", "1", "2", "3"]} suffix="+ baths" /><Select label="Max Price" value={priceMax} setValue={setPriceMax} options={["Any", "75000", "125000", "150000", "200000"]} suffix=" max" money /><Select label="Min Sq. Ft." value={sqftMin} setValue={setSqftMin} options={["Any", "750", "1000", "1400", "1800"]} suffix="+ sq. ft." /><label className="text-sm font-black text-ehsBlack md:col-span-2">Sort<select value={sort} onChange={(e) => setSort(e.target.value as Sort)} className="mt-2 w-full rounded-2xl border border-borderGray bg-white px-4 py-3 font-semibold text-ehsBlack"><option value="newest">Newest</option><option value="price-asc">Price: low to high</option><option value="price-desc">Price: high to low</option><option value="sqft-asc">Square footage: low to high</option><option value="sqft-desc">Square footage: high to low</option><option value="beds-asc">Bedrooms: low to high</option><option value="beds-desc">Bedrooms: high to low</option></select></label><div className="grid grid-cols-2 gap-2 md:col-span-4">{([['featured','Featured'],['onDisplay','On Display'],['specialOffer','Special Offer'],['newArrival','New Arrival']] as const).map(([key,label]) => <button key={key} type="button" onClick={() => setFlags(v => ({...v,[key]: !v[key]}))} className={`rounded-full px-4 py-2 text-sm font-black transition ${flags[key] ? "bg-ehsBlue text-white" : "bg-ehsSoftBlue text-ehsBlack hover:bg-ehsLightBlue/50"}`}>{label}</button>)}</div></div><p className="mt-4 text-sm font-semibold text-ehsBlack/65">Showing {filteredHomes.length} of {homes.length} homes.</p></div><div className="mt-8 grid gap-6 lg:grid-cols-2">{filteredHomes.map((home) => <HomeCard key={home.id} home={home} />)}</div></section>;
}
function Select({ label, value, setValue, options, suffix, money = false }: { label: string; value: string; setValue: (v: string) => void; options: string[]; suffix: string; money?: boolean }) { return <label className="text-sm font-black text-ehsBlack">{label}<select value={value} onChange={(e) => setValue(e.target.value)} className="mt-2 w-full rounded-2xl border border-borderGray bg-white px-4 py-3 font-semibold text-ehsBlack">{options.map(o => <option key={o} value={o}>{o === "Any" ? "Any" : `${money ? "$" + Number(o).toLocaleString() : o}${suffix}`}</option>)}</select></label>; }
