"use client";

import Link from "next/link";
import { useState } from "react";
import { SiteLogo } from "@/components/SiteLogo";

const nav = [["Homes", "/homes"], ["Featured Homes", "/featured-homes"], ["Special Offers", "/special-offers"], ["Financing", "/financing"], ["Delivery & Setup", "/delivery-setup"], ["How It Works", "/how-it-works"], ["Contact", "/contact"]];

export function SiteHeader() {
  const [open, setOpen] = useState(false);
  return <><header className="sticky top-0 z-20 border-b border-borderGray bg-white/95 backdrop-blur"><nav className="mx-auto max-w-7xl px-4 py-3" aria-label="Main navigation"><div className="flex items-center justify-between gap-4"><Link href="/" aria-label="Easy HomeSource home" onClick={() => setOpen(false)} className="shrink-0"><SiteLogo /></Link><div className="hidden items-center gap-4 whitespace-nowrap text-sm font-bold text-ehsBlack lg:flex">{nav.map(([label, href]) => <Link key={href} href={href} className="transition hover:text-ehsBlue">{label}</Link>)}<a className="rounded-full bg-ehsBlue px-5 py-3 font-black text-white shadow-sm transition hover:bg-ehsMediumBlue focus:outline-none focus:ring-4 focus:ring-ehsLightBlue/60" href="tel:+13525588888">Call/Text 352-558-8888</a></div><button type="button" className="rounded-full border border-borderGray bg-white px-4 py-2 text-sm font-black text-ehsBlack shadow-sm transition hover:border-ehsBlue hover:text-ehsBlue focus:outline-none focus:ring-4 focus:ring-ehsLightBlue/60 lg:hidden" aria-expanded={open} onClick={() => setOpen((value) => !value)}>Menu</button></div>{open && <div className="mt-4 grid gap-2 rounded-3xl border border-borderGray bg-ehsSoftBlue p-3 text-sm font-black text-ehsBlack shadow-lg lg:hidden">{nav.map(([label, href]) => <Link key={href} href={href} onClick={() => setOpen(false)} className="rounded-2xl bg-white px-4 py-3 transition hover:text-ehsBlue">{label}</Link>)}<a onClick={() => setOpen(false)} className="rounded-2xl bg-ehsBlue px-4 py-3 text-center text-white transition hover:bg-ehsMediumBlue" href="tel:+13525588888">Call/Text 352-558-8888</a></div>}</nav></header><div className="fixed inset-x-0 bottom-0 z-30 grid grid-cols-3 border-t border-borderGray bg-white text-center text-sm font-black shadow-2xl lg:hidden"><a className="py-3 text-ehsBlue" href="tel:+13525588888">Call</a><a className="border-x border-borderGray py-3 text-ehsBlue" href="sms:+13525588888">Text</a><Link className="bg-ehsBlue py-3 text-white" href="/contact">Get Pricing</Link></div></>;
}
