import type { ReactNode } from "react";
import { siteInfo } from "@/data/site";

export const metadata = { title: "Terms & Conditions", description: "Easy HomeSource website terms and conditions." };

export default function TermsPage() {
  return <main className="px-4 py-12"><section className="mx-auto max-w-4xl rounded-[2rem] bg-white p-8 shadow-sm ring-1 ring-ehsBlue/10"><p className="font-black text-ehsDeepBlue">Easy HomeSource</p><h1 className="mt-2 text-4xl font-black text-ehsNavy">Terms &amp; Conditions</h1><p className="mt-3 text-sm font-semibold text-ehsNavy/60">Last updated: July 7, 2026</p><div className="mt-8 space-y-6 leading-8 text-ehsNavy/75"><p>These terms apply to your use of the Easy HomeSource website. By using this website or submitting a request, you agree to use the site for lawful purposes and understand that website information is provided for general shopping and informational use.</p><Section title="Home information and pricing">Photos, floor plans, features, dimensions, pricing, availability, and descriptions may be representative and may change without notice. Final pricing requires a written quote and may depend on selected options, taxes, fees, delivery, setup, permits, site conditions, lender approval, and other project details.</Section><Section title="Financing information">Financing information is provided for discussion purposes only and is not a loan approval, guarantee, or commitment to lend. Credit approval, down payment, rates, terms, and program availability are determined by lenders or financing partners.</Section><Section title="Delivery, setup, and permits">Delivery, setup, installation, utility connections, inspections, and permitting requirements vary by location and property. Easy HomeSource may help explain next steps, but project requirements and costs must be confirmed for your specific site.</Section><Section title="Website content">We work to keep website content accurate, but errors may occur. Easy HomeSource may update or remove content at any time. Manufacturer media and third-party media are used for shopping reference and may show homes with options, décor, colors, or features that differ from available inventory.</Section><Section title="Contact and SMS consent">When you submit a form or contact us, you authorize Easy HomeSource to respond by phone, email, call, or text about your inquiry. Message and data rates may apply. Consent is not a condition of purchase, and you may opt out of marketing communications at any time.</Section><Section title="Contact">Questions about these terms can be sent to {siteInfo.email}, by calling {siteInfo.phoneDisplay}, or by visiting {siteInfo.address}.</Section></div></section></main>;
}

function Section({ title, children }: { title: string; children: ReactNode }) { return <section><h2 className="text-2xl font-black text-ehsNavy">{title}</h2><p className="mt-2">{children}</p></section>; }
