export const metadata = { title: "Terms & Conditions", description: "Easy HomeSource terms and conditions." };

const termsSections = [
  { heading: "Trove Homes, Inc. – General Terms and Conditions", body: ["Last updated: Feb 3, 2026", "Please read these terms and conditions carefully before using Our Service.", "These General Terms and Conditions apply to all users of our Service. For users of licensed software products, these terms are supplemented by License Terms of Service. For information about SMS and email communications, please see SMS and Email Communication Terms."] },
  { heading: "Interpretation and Definitions", body: ["Words with initial capital letters have meanings defined under these conditions and have the same meaning whether singular or plural.", "Company refers to Trove Homes, Inc., 104 Birch Way, San Rafael, CA 94903. Country refers to California, United States. Service refers to the Website. Website refers to Trove, accessible from https://buildtrove.com/. You means the individual accessing or using the Service, or the company or other legal entity on behalf of which such individual is accessing or using the Service."] },
  { heading: "Acknowledgment", body: ["These Terms and Conditions govern the use of this Service and set out the rights and obligations of all users regarding the use of the Service.", "Your access to and use of the Service is conditioned on acceptance of and compliance with these Terms and Conditions. If You disagree with any part of these Terms and Conditions, You may not access the Service.", "You represent that you are over the age of 18. The Company does not permit those under 18 to use the Service.", "Your access to and use of the Service is also conditioned on acceptance of and compliance with the Privacy Policy of the Company."] },
  { heading: "Links to Other Websites", body: ["Our Service may contain links to third-party websites or services that are not owned or controlled by the Company.", "The Company has no control over and assumes no responsibility for the content, privacy policies, or practices of third-party websites or services. We strongly advise You to read the terms and privacy policies of any third-party websites or services You visit."] },
  { heading: "Termination", body: ["We may terminate or suspend Your access immediately, without prior notice or liability, for any reason whatsoever, including without limitation if You breach these Terms and Conditions.", "Upon termination, Your right to use the Service will cease immediately."] },
  { heading: "Limitation of Liability", body: ["The entire liability of the Company and any of its suppliers under any provision of these Terms and Your exclusive remedy shall be limited to the amount actually paid by You through the Service or 100 USD if You have not purchased anything through the Service.", "To the maximum extent permitted by applicable law, the Company or its suppliers shall not be liable for special, incidental, indirect, or consequential damages."] },
  { heading: "AS IS and AS AVAILABLE Disclaimer", body: ["The Service is provided to You AS IS and AS AVAILABLE and with all faults and defects without warranty of any kind.", "To the maximum extent permitted under applicable law, the Company disclaims all warranties, whether express, implied, statutory, or otherwise, with respect to the Service."] },
  { heading: "Governing Law and Disputes", body: ["The laws of the Country, excluding conflict of law rules, shall govern these Terms and Your use of the Service.", "If You have any concern or dispute about the Service, You agree to first try to resolve the dispute informally by contacting the Company."] },
  { heading: "United States Legal Compliance", body: ["You represent and warrant that You are not located in a country subject to a United States government embargo or listed on any United States government list of prohibited or restricted parties."] },
  { heading: "Copyright Infringement (DMCA)", body: ["Trove Homes, Inc. respects the intellectual property of others. Notices of alleged infringement may be sent to legal@buildtrove.com with the information required by the DMCA."] },
  { heading: "Changes to These Terms and Conditions", body: ["We reserve the right, at Our sole discretion, to modify or replace these Terms at any time. By continuing to access or use Our Service after revisions become effective, You agree to be bound by the revised terms."] },
  { heading: "Contact Us", body: ["If you have any questions about these Terms and Conditions, You can contact us by email at support@buildtrove.com or by phone number at 628-400-3733."] }
];

export default function TermsPage() {
  return <main className="px-4 py-12"><article className="mx-auto max-w-4xl rounded-[2rem] border border-borderGray bg-white p-8"><p className="font-black text-ehsBlue">Terms &amp; Conditions</p>{termsSections.map((section, index) => <section key={section.heading} className={index === 0 ? "mt-2" : "mt-8"}><h1 className={index === 0 ? "text-4xl font-black text-ehsBlack" : "text-2xl font-black text-ehsBlack"}>{section.heading}</h1><div className="mt-4 space-y-4 leading-8 text-ehsBlack/75">{section.body.map((paragraph) => <p key={paragraph}>{paragraph}</p>)}</div></section>)}</article></main>;
}
