import type { HomeMediaManifest } from "@/data/homeMedia";

/**
 * Generated by scripts/import-manufacturer-media.ts.
 * Manufacturer media is lower-precedence than curated EHS overrides.
 */
export const manufacturerMedia: HomeMediaManifest = {};
